import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';
import '../../firebase_options.dart';

/**
 * Firebase Configuration
 * Initializes Firebase for the application
 * Uses firebase_options.dart generated by flutterfire configure
 */
class FirebaseConfig {
  static bool _initialized = false;

  static Future<void> initialize() async {
    if (_initialized) {
      return;
    }

    try {
      // Check if Firebase is already initialized
      if (Firebase.apps.isEmpty) {
        // Initialize Firebase with options from firebase_options.dart
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );
      }
      _initialized = true;
    } catch (e) {
      // Don't throw - allow app to continue even if Firebase fails
      // This is important for development when Firebase might not be configured
      debugPrint('Firebase initialization error: $e');
      _initialized = false;
    }
  }

  static bool get isInitialized => _initialized;
}
